HW5 is completed
moronvv/otus_golang_hw pull request #5
Opened 2023-07-17 19:17 UTC by moronvv

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-07-17 19:20 UTC, moronvv commented on hw05_parallel_execution/run.go
> +				// running.Wait()
@dshemin к сожалению я так и не одолел эту задачу... Мне понадобится ваша помощь.

Я так и не догадался, как корректно завершить уже начатые таски после получения m ошибок. При поптыке синхронизироваться через wg тесты повисают (где-то, видимо, ловлю deadlock)

2023-07-17 21:05 UTC, moronvv commented
Написал чуть поаккуратней, взяв за основу workers pool. Результат тот же

2023-07-18 05:32 UTC, dshemin requested changes

2023-07-18 05:32 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	tasksCh := make(chan Task, len(tasks))
Важно:
 
 Нет проверки что n меньше или равно 0. Надо добавить проверку и написать тест.

2023-07-18 05:32 UTC, dshemin commented on hw05_parallel_execution/run.go
> +func worker(tasks chan Task, wg *sync.WaitGroup, allTasksDone chan struct{}, taskErr chan error, quit chan struct{}) {
Важно:

Не надо передавать sync.WaitGroup в качестве аргумента. Он никак не вляет на логику работы функции, только создаёт не нужную/ зависимость.

2023-07-18 05:32 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	allTasksDone := make(chan struct{})
Важно:

Зачем нам этот канал? Судя по логике туда будет что-то записано только если taskCh будет закрыт. Но этот канал используется чтобы закрыть taskCh.

2023-07-18 05:32 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	quit := make(chan struct{})
Важно:

quit канал не нужен. Если мы хотим завершить горутину, которая обрабатывает какой-то канал, достаточно закрыть этот канал и всё.

2023-07-18 05:32 UTC, dshemin commented on hw05_parallel_execution/run.go
> +	for {
Критично:

В вашей текущей логике получается так:
1. Мы отправляем задачи в канал.
2. Потом обрабатываем ошибки. Кстати из-за этого и того что канал с ошибка не буферезирован - у вас и происходит зависание. Если все задачи вернут ошибки, они заблокируют всех воркеров.

Надо чтобы в случае накопления определённого количества ошибок мы СРАЗУ завершили обработку.

2023-07-18 11:31 UTC, moronvv commented
@dshemin Спасибо за подсказки! Вроде разобрался

2023-07-18 12:39 UTC, dshemin approved these changes

2023-07-18 12:45 UTC, merged